version: '3.8'
services:
  data-service:
    image: data-service
    env_file: datamanagement\datafile.env
    ports:
      - "8001:8001"
    networks:
      - app-network

  main-app:
    image: core-service
    ports:
      - "8000:8000"
    depends_on:
      - data-service 
    env_file: coreservices\myenv.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
